site_name: File Downloads Statistics
nav:
  - Home: index.md
  - General Configurations: param-config.md
  - Nextflow Config: nextflow-slurm-config.md
  - GitLab Config: gitlab-config.md
  - Limitations: limitations.md
theme:
  name: material
  palette:
    scheme: slate
    primary: green

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

