site_name: File Downloads Statistics
docs_dir: docs
nav:
  - Home: index.md
  - Get Started:
      - get_started/installation.md
  - Workflow:
      - workflow/overview.md
      - workflow/gitlab-config.md
      - workflow/nextflow-slurm-config.md
      - workflow/param-config.md
  - Reports:
      - report/report-interpretation.md
      - report/report-customization.md
  - Miscellaneous:
      - misc/log-files.md
      - misc/workflow.md
      - misc/limitations.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/PRIDE-Archive/file-download-stat
extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js
